CTRL_C = 3         # Ctrl-c
CTRL_H = 8         # ctrl-h
CTRL_J = 10        # ctrl-h
CTRL_K = 11        # ctrl-h
CTRL_L = 12        # ctrl-h
CTRL_F = 6        # ctrl-f
ENTER = 13         # Enter
CTRL_U = 21        # Ctrl+u
ESC = 27           # Escape
BACKSPACE =  127   # Backspace
TAB = 9            # Tab
RIGHT = -1     	   # FAKE CODE to abstract away the fact that a multibyte string is needed to represent arrow keys 
DOWN = -2          # same
UP = -3		   # same
LEFT = -4          # same
SHIFTTAB = -5      # same
SHIFTENTER = -6
SPACE = 32
ANTISLASH = 47
